@post_id = 6a3d18b40a49e52d67d80a9b
@auth_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2YTNhODQ4ZTExOGE0NTkyNjM3ZTRlNWIiLCJpYXQiOjE3ODIzODY1NDN9.mxb43hX05wE-A3IGnelcNMjTT5nDkV-CCfS-dHUJboM
# Helper request to fetch all posts
GET http://localhost:3003/api/blogs/

###
# Helper request to fetch one post
GET http://localhost:3003/api/blogs/{{post_id}}

###
# Actual DELETE request, first without an auth token
DELETE http://localhost:3003/api/blogs/{{post_id}}

###
DELETE http://localhost:3003/api/blogs/{{post_id}}
Authorization: Bearer {{auth_token}}