# @auth_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2YTNhODQ4ZTExOGE0NTkyNjM3ZTRlNWIiLCJpYXQiOjE3ODIzODY1NDN9.mxb43hX05wE-A3IGnelcNMjTT5nDkV-CCfS-dHUJboM
@auth_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2YTNhODQ4ZTExOGE0NTkyNjM3ZTRlNWIiLCJpYXQiOjE3ODM0MzMzMTJ9.bwvAyV6sziehvRtWWjuFrpKl7HqOXs4gMUwp-I5Gh2M
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Esimerkkiblogi 3 USERMODE",
    "author": "Erkki Esimerkki",
    "url": "https://examp.le.doesnotexist/foobar",
    "likes": 11
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer foobar

{
    "title": "Esimerkkiblogi 3 USERMODE",
    "author": "Erkki Esimerkki",
    "url": "https://examp.le.doesnotexist/foobar",
    "likes": 11
}

### 

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "title": "Esimerkkiblogi {{$datetime rfc1123}}",
    "author": "Erkki Esimerkki",
    "url": "https://examp.le.doesnotexist/foobar",
    "likes": {{$randomInt 0 5}}
}

###
@post_id = 6a3d2d9ad3a9e607a42a5328
POST http://localhost:3003/api/blogs/{{post_id}}/comments
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "content": "Comment on {{$datetime rfc1123}}"
}